[main]
# The default PPD profile
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
# PPD = TuneD
power-saver=z13-power-saver
balanced=z13-balanced
performance=z13-performance

[battery]
# PPD = TuneD
power-saver=z13-power-saver
balanced=z13-balanced
performance=z13-performance
